'use client';

import React from 'react';
import { ArrowLeft, BookOpen, Scale, Award, Video, Info, FileText } from 'lucide-react';
import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="relative flex-1 flex flex-col bg-background min-h-screen">
      {/* Mouse Reactive Background / Grid */}
      <div className="fixed inset-0 grid-bg pointer-events-none z-0 opacity-[0.03]"></div>

      <div className="relative z-10 flex-1 mx-auto max-w-5xl w-full px-4 py-12 sm:px-6 lg:px-8">
        
        {/* Header Block */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 border-b-4 border-primary pb-8 mb-12">
          <div className="flex items-center gap-4">
            <Link
              href="/dashboard"
              className="border-3 border-primary bg-card p-3 text-primary hover:bg-accent transition-all cursor-pointer hover:translate-x-[-2px] hover:translate-y-[-2px] hover:bauhaus-shadow-sm"
              title="Return to Workspace"
            >
              <ArrowLeft className="h-5 w-5" />
            </Link>
            <div>
              <h1 className="text-3xl sm:text-4xl font-black font-headline uppercase tracking-widest text-primary">
                Terms of Service
              </h1>
              <p className="text-xs sm:text-sm font-body font-semibold text-muted-foreground uppercase tracking-wider mt-1">
                The Bauhaus OS License for Digital Synthesis.
              </p>
            </div>
          </div>
          <div className="text-[10px] font-headline uppercase font-bold text-muted-foreground border-2 border-primary bg-card px-3 py-1.5 self-start md:self-auto">
            Last Updated: June 1, 2026
          </div>
        </div>

        {/* Content Layout Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Main Legal Content */}
          <div className="lg:col-span-2 flex flex-col gap-8">
            
            {/* Section: License */}
            <div className="bg-card border-3 border-primary p-6 sm:p-8 bauhaus-shadow-sm">
              <h2 className="text-sm font-black uppercase tracking-widest font-headline text-primary mb-4 flex items-center gap-2">
                <BookOpen className="h-5 w-5 text-secondary" />
                <span>1. Operating License & Usage</span>
              </h2>
              <div className="font-body text-xs sm:text-sm text-primary leading-relaxed space-y-4 font-medium">
                <p>
                  By accessing and utilizing Promptube (the "Service" or "Application"), you enter into a binding 
                  agreement governed by these Terms of Service. Promptube provides a client-side Bauhaus OS platform 
                  designed to synthesize video materials and textual sources into structured prompts for engineering use.
                </p>
                <p>
                  You are granted a non-exclusive, non-transferable, revocable license to run this tool locally 
                  for personal or professional digital synthesis.
                </p>
              </div>
            </div>

            {/* Section: Ownership */}
            <div className="bg-card border-3 border-primary p-6 sm:p-8 bauhaus-shadow-sm">
              <h2 className="text-sm font-black uppercase tracking-widest font-headline text-primary mb-4 flex items-center gap-2">
                <Award className="h-5 w-5 text-secondary" />
                <span>2. Synthesis & Intellectual Property</span>
              </h2>
              <div className="font-body text-xs sm:text-sm text-primary leading-relaxed space-y-4 font-medium">
                <p>
                  <strong>Your Prompts, Your Assets:</strong> Promptube claims zero ownership or intellectual property 
                  rights over the prompts, configurations, or structured cards synthesized using the Service. 
                  All custom files, outputs, and exports generated by your actions are 100% your property.
                </p>
                <p>
                  You are solely responsible for ensuring that your synthesized outputs do not violate the patents, 
                  trademarks, or copyrights of external third parties.
                </p>
              </div>
            </div>

            {/* Section: YouTube compliance */}
            <div className="bg-card border-3 border-primary p-6 sm:p-8 bauhaus-shadow-sm">
              <h2 className="text-sm font-black uppercase tracking-widest font-headline text-primary mb-4 flex items-center gap-2">
                <Video className="h-5 w-5 text-secondary" />
                <span>3. Third-Party Media Compliance</span>
              </h2>
              <div className="font-body text-xs sm:text-sm text-primary leading-relaxed space-y-4 font-medium">
                <p>
                  Promptube allows users to input public media links (specifically YouTube URLs) to retrieve transcripts 
                  for translation and prompt engineering.
                </p>
                <p>
                  You represent and warrant that your access to and synthesis of such public media material is in full 
                  compliance with the respective host's guidelines, licensing terms, and the 
                  <a 
                    href="https://www.youtube.com/t/terms" 
                    target="_blank" 
                    rel="noopener noreferrer" 
                    className="text-secondary hover:underline font-bold"
                  > YouTube Terms of Service</a>. 
                  Promptube does not condone or support copyright infringement or intellectual property piracy.
                </p>
              </div>
            </div>

            {/* Section: Disclaimer */}
            <div className="bg-card border-3 border-primary p-6 sm:p-8 bauhaus-shadow-sm">
              <h2 className="text-sm font-black uppercase tracking-widest font-headline text-primary mb-4 flex items-center gap-2">
                <Scale className="h-5 w-5 text-secondary" />
                <span>4. Limitation of Liability & Warranties</span>
              </h2>
              <div className="font-body text-xs sm:text-sm text-primary leading-relaxed space-y-4 font-medium">
                <p>
                  THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT WARRANTIES OF ANY KIND, 
                  EITHER EXPRESSED OR IMPLIED. 
                </p>
                <p>
                  Promptube does not warrant that transcript extraction pipelines will operate without interruption, 
                  or that the AI summary structures generated by third-party cognitive engines (Google Gemini) will be free 
                  of logical errors. Under no circumstances shall Promptube or its contributors be held liable for any data 
                  loss, database corruption, or billing charges incurred through your personal use of custom Gemini API tokens.
                </p>
              </div>
            </div>

          </div>

          {/* Sidebar Panel - Terms Info */}
          <div className="flex flex-col gap-6">
            
            {/* Bauhaus Card */}
            <div className="bg-tertiary border-3 border-primary p-6 text-white bauhaus-shadow">
              <h3 className="text-base font-black uppercase tracking-widest font-headline mb-4 flex items-center gap-1.5">
                <Info className="h-5 w-5" />
                <span>Key Terms</span>
              </h3>
              
              <div className="flex flex-col gap-4 font-headline uppercase font-bold text-xs">
                
                <div className="flex items-center gap-3 border-b-2 border-white/20 pb-3">
                  <div className="h-5 w-5 border-2 border-white bg-white text-tertiary flex items-center justify-center text-[10px] font-black shrink-0">1</div>
                  <span>Owner Rights Maintained</span>
                </div>

                <div className="flex items-center gap-3 border-b-2 border-white/20 pb-3">
                  <div className="h-5 w-5 border-2 border-white bg-white text-tertiary flex items-center justify-center text-[10px] font-black shrink-0">2</div>
                  <span>Respect Media Rights</span>
                </div>

                <div className="flex items-center gap-3 border-b-2 border-white/20 pb-3">
                  <div className="h-5 w-5 border-2 border-white bg-white text-tertiary flex items-center justify-center text-[10px] font-black shrink-0">3</div>
                  <span>Provided "As-Is"</span>
                </div>

                <div className="flex items-center gap-3 pb-1">
                  <div className="h-5 w-5 border-2 border-white bg-white text-tertiary flex items-center justify-center text-[10px] font-black shrink-0">4</div>
                  <span>Client-Side Execution</span>
                </div>

              </div>
            </div>

            {/* Read Privacy Card */}
            <div className="bg-card border-3 border-primary p-6 flex flex-col gap-4">
              <h3 className="text-xs font-black uppercase tracking-widest font-headline text-primary">
                Review our privacy framework
              </h3>
              <p className="text-[11px] font-body font-medium text-muted-foreground leading-relaxed">
                Learn exactly how we implement our local-first security measures to protect your API keys and synthesized outputs.
              </p>
              <Link
                href="/privacy"
                className="w-full text-center border-2 border-primary bg-accent text-primary font-headline font-black uppercase text-xs py-3 hover:bg-primary hover:text-accent-foreground transition-all cursor-pointer"
              >
                Read Privacy Policy
              </Link>
            </div>

          </div>

        </div>

      </div>
    </div>
  );
}
